### ISSUE TITLE
Создать скрипты train.py, predict.py

### ISSUE THREAD

**Issue by sabal202** [sabal202/tinkoff_cafe#17]
Скрипты предоставляют API для взаимодействия тестирующей системы и нашей модели.

----

Аргументы `train.py` (название файлов для обучения модели):

- `--train <train_fn.csv>` 
- `--menu <menu_train_fn.csv>` - меню по дням
- `--tags <menu_tagged_fn.csv>` 
- `--model <model_fn.py>`  - необязательный аргумент (по умолчанию `"solution.py"`)

`train.py` проводит обучение модели по предоставленным данным.

Пример вызова:
`python train.py --train "../data/train.csv" --menu "../data/menu_train.csv" --tags "../data/menu_tagged.csv"`

Аргументы `predict.py` (название файлов для обучения модели):

- `--test <test_fn.csv>` 
- `--menu <menu_test_fn.csv>` - меню по дням
- `--out <prediction_fn>` - по умолчанию `prediction.csv`
- `--model <model_fn.py>`  - необязательный аргумент (по умолчанию `"solution.py"`)

`predict.py` - возвращает таблицу такого же формата, как и `train.csv`

Пример вызова:
`python predict.py --test "../data/test.csv" --menu "../data/menu_train.csv" --out "prediction.csv"`

**Comment by svkov** [comment]
Это занесли куда-нибудь в Wiki?
